name: project
dependencies:
  - python=3.6.5
  - pillow==6.2.1
  - pytorch==1.3.1
  - tensorflow==1.15
  - scikit-learn
  - numpy
  - scipy
  - pandas
  - matplotlib==3.1.0
  - pytest
  - pip
  - pip:
    - pyspark==3.0.1
    - sparkdl
    - keras
    - tensorframes
    - kafka-python
    - jieba
